#!/bin/bash
if [[ -z $1 ]]; then
	echo "Usage:"
	echo "$0 \"PostTitle\""
	echo "Example: $0 \"A very cool post\""
	exit 1
fi
newPostFile=_posts/$(date +"%Y-%m-%d-$1.html")
vim "$newPostFile"
git add "$newPostFile"
git commit -m"$1"
git push
